### ISSUE TITLE
test_twine fails with existing /usr/bin/twine

### ISSUE THREAD

**Issue by blueyed** [zsimic/setupmeta#35] opened 2019-08-30 13:16 UTC
I could patch `setupmeta.which` to return `False` for `run_setup_py(["twine", "--egg=all"], "twine is not installed")`, but later invocations should also use the mocked (copied) version then.

**Comment by zsimic** [comment] 2019-09-04 01:45
Ah very good point, need better mocking there indeed for that test

**Comment by blueyed** [comment] 2019-09-16 23:49
#36 improved it, still fails later though:
```
tests/test_commands.py::test_twine FAILED                                             [100%]

========================================= FAILURES ==========================================
________________________________________ test_twine _________________________________________

sample_project = '/tmp/tmp2sfg24qr/sample'

    @pytest.mark.skipif(setupmeta.WINDOWS, reason="No support for twine on windows")
    def test_twine(sample_project):
        with patch.dict(os.environ, {"SETUPMETA_TWINE": "/dev/null/no-twine"}):
            run_setup_py(["twine"], "Specify at least one of: --egg, --dist or --wheel")
            run_setup_py(["twine", "--egg=all"], "twine is not installed")
    
        mocked_twine = os.path.join(sample_project, "mocked-twine")
        shutil.copy2(setupmeta.project_path("tests", "mock-twine"), mocked_twine)
    
        with patch.dict(os.environ, {"SETUPMETA_TWINE": "mocked-twine"}):
            run_setup_py(
                ["twine", "--egg=all"],
                """
                    Dryrun, use --commit to effectively build/publish
                    Would build egg distribution: .*python.* setup.py bdist_egg
                    Would upload to PyPi via twine
                """,
            )
    
            run_setup_py(
                ["twine", "--commit", "--egg=all", "--wheel=1.0"],
                """
                    python.* setup.py bdist_egg
                    Uploading to PyPi via twine
                    Running: <target>/mocked-twine upload <target>/dist/sample-0.1.0-.+.egg
                    Deleting <target>/build
>               """,
            )

…/Vcs/setupmeta/tests/test_commands.py:289: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = ['twine', '--commit', '--egg=all', '--wheel=1.0']
expected = ['', '                python.* setup.py bdist_egg', '                Uploading to PyPi via twine', '                Ru...get>/mocked-twine upload <target>/dist/sample-0.1.0-.+.egg', '                Deleting <target>/build', '            ']
folder = None

    def run_setup_py(args, expected, folder=None):
        expected = expected.splitlines()
        output = conftest.run_setup_py(folder or os.getcwd(), *args)
        for line in expected:
            line = line.strip()
            if not line:
                continue
            m = re.search(line, output)
>           assert m, "'%s' not present in output of '%s': %s" % (line, " ".join(args), output)
E           AssertionError: 'Running: <target>/mocked-twine upload <target>/dist/sample-0.1.0-.+.egg' not present in output of 'twine --commit --egg=all --wheel=1.0': Building egg distribution...
E             Running: /tmp/tox…/Vcs/setupmeta/py37/bin/python setup.py bdist_egg
E             Uploading to PyPi via twine...
E             Running: <target>/mocked-twine upload <target>/dist/sample-0.0.0.dirty-py3.7.egg
E             Deleting <target>/build...
E           assert None

…/Vcs/setupmeta/tests/test_commands.py:24: AssertionError
----------------------------------- Captured stdout setup -----------------------------------
Running: git init
Running: git add sample.py .gitignore requirements.txt setup.py setup.cfg
Running: git commit -m "Initial commit"
Running: git tag -a v0.1.0 -m "Version 2.4.2"
===================================== warnings summary ======================================
tests/test_commands.py::test_twine
  …/Vcs/setupmeta/tests/test_commands.py:24: PytestAssertRewriteWarning: asserting the value None, please use "assert is None"
    assert m, "'%s' not present in output of '%s': %s" % (line, " ".join(args), output)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================= 1 failed, 54 deselected, 1 warnings in 1.09s ========================
ERROR: InvocationError for command /tmp/tox…/Vcs/setupmeta/py37/bin/pytest -k test_twine -vv (exited with code 1)
__________________________________________ summary __________________________________________
ERROR:   py37: commands failed
```
(using `tox -e py37 -- -k test_twine -vv`)

**Comment by zsimic** [comment] 2019-09-17 03:20
Ah, so from your output, looks like the `mocked-twine` is now working as expected, however you seem to get this:
```
Running: .../mocked-twine .../sample-0.0.0...
```

Instead of the expected:
```
Running: .../mocked-twine .../sample-0.1.0...
```

Ie: in your case, it got the version wrong.

The test should basically create a temp folder, with a few sample files in it, and assign a tag `v0.1.0`. Somehow, you get a different tag.

The sample git repo is created by `sample_project()` in `conftest.py`, and the tagging should be happening line 50 of `conftest.py`. Something in your setup is changing that apparently. Only debugger can tell us what I think.

**Comment by zsimic** [comment] 2020-05-04 19:40
Going to close this one as can't reproduce.

I just added an explicit `git config` call in test setup: https://github.com/zsimic/setupmeta/commit/04cc94db33436e3567a04f17f079b779ae36d79d

It's possible that you have a version of git that I didn't have, just realized today some git setups complain about missing name/email, it could be what was making your test run fail before.

**Closed by zsimic** 2020-05-04 19:40 UTC
